### ISSUE TITLE
LacunaStories- Annotations Dashboard has spinning wheel

### ISSUE THREAD

**Issue by pguerr061703** [PoeticMediaLab/LacunaStories#167] opened 2016-10-20 00:02 UTC
I am using Drupal 7.5 (for LacunaStories)
Updated some system modules within LacunaStories (which is using Drupal 7.50)
Now when I click on Reflect-->Annotations Dashboard, I just see a spinning wheel. No chart or graph to display. (See attached)
I don't know how to fix, as I didn't backup the database.
I don't know what module did this...
Can anyone please HELP me find out why the Reflect-->Annotations Dashboard just has a spinning wheel, instead of displaying chart or some type of display? Is this java related

I'm running Ubuntu 16.04LTS

Any ANY Help would be greatly appreciated

**Comment by mwidner** [comment] 2016-10-20 00:06
Hi! Thanks for the detailed bug report. The problem is because when you updated the site, you no doubt updated the d3 module, too. Unfortunately, the latest version of that module is broken and the maintainer has yet to provide a fix. So, you'll need to change that module to the older version. You can copy the correct version from the Lacuna repository itself. Let me know if you have any questions or this doesn't fix it. 

P. S.  The next version of Lacuna will prevent updating the d3 module.

**Comment by pguerr061703** [comment] 2016-10-20 00:23
Thanks!!!!! How do I get the OLD d3 module?
Where can I go for that ?
How to install it back on Ubuntu via command-line
Sorry..but I'M a newbie on the module install/deinstall

**Comment by mwidner** [comment] 2016-10-20 02:26
You can get the old d3 module here: 

https://github.com/PoeticMediaLab/LacunaStories/tree/develop/sites/all/modules/contrib/d3

If you installed it using git, then you can check out the old module from the repo. If you haven't committed the upgrades, then from the command-line inside your Lacuna directory this should do it:

`git checkout master sites/all/modules/contrib/d3`

**Comment by pguerr061703** [comment] 2016-10-20 02:48
I did NOT install it using git command-line (I did the update of modules thru Lacuna interface).
Still not sure how to do this... (see below)
root@ace-admin03:/var/www/html#   git checkout master sites/all/modules/contrib/d3
error: pathspec 'master' did not match any file(s) known to git.
root@ace-admin03:/var/www/html#

**Comment by pguerr061703** [comment] 2016-10-20 02:52
By the way, I don't see a way to download the d3 module folder from that link. No download button. Can you help me download this module, and I will attempt to install it (either thru git command-line or Lacuna interface (update module)

https://github.com/PoeticMediaLab/LacunaStories/tree/develop/sites/all/modules/contrib/d3

**Comment by mwidner** [comment] 2016-10-20 03:02
If you downloaded the code as a zip, then you should have a sub-folder in that zip that matches that path. You can always re-download the zipfile if you don't have it, unzip it somewhere else, then copy the d3 directory into your site's directory.

Or you can try git by doing this:
`git init
git remote add origin https://github.com/PoeticMediaLab/LacunaStories.git
git fetch origin
git checkout origin/master -- sites/all/modules/contrib/d3 `

I think that's right. Best of luck.

**Comment by pguerr061703** [comment] 2016-10-20 03:57
Thanks. That is weird. I tried the commands above, but the spinning wheel is still there.
I found the Lacuna zip file and copied all contents of d3 folder to /var/www/html/sites/all/modules/contrib/d3   ---> rebooted and STILL spinning wheel

I tried to clear cache from Dashboard...still spinning wheel. 
Maybe I'm missing something else?

Looking at uninstalling D3  from Lacuna (uninstall modules dropdown)

**Comment by pguerr061703** [comment] 2016-10-20 12:32
I saw a .drush-lock-update in my old d3 directory (d3.ORIG) /var/www/html/sites/all/modules/contrib/d3.orig/.drush-lock-update

Once I ran the fetch commands, and it created a d3 directory ( i ran a diff between directories )
root@ace-admin03:/var/www/html/sites/all/modules/contrib# diff d3 d3.ORIG
Only in d3.ORIG: .drush-lock-update
Common subdirectories: d3/includes and d3.ORIG/includes
Common subdirectories: d3/js and d3.ORIG/js
Common subdirectories: d3/libraries and d3.ORIG/libraries
Common subdirectories: d3/modules and d3.ORIG/modules
Common subdirectories: d3/tests and d3.ORIG/tests


root@ace-admin03:/var/www/html/sites/all/modules/contrib# mv d3.fix /var/tmp
root@ace-admin03:/var/www/html/sites/all/modules/contrib# ls -l | grep ^d | grep d3
drwxr-xr-x  7 root  root    4096 Oct 20 08:15 d3
drwxrwxrwx  7 root  root    4096 Oct 19 23:29 d3.ORIG
root@ace-admin03:/var/www/html/sites/all/modules/contrib#

The only difference is the the LOCK file in the original d3 (now called d3.ORIG) directory
Could that be causing the problem ?? (see below)
https://docs.acquia.com/articles/using-drush-lock-files-contributed-modules

**Comment by mwidner** [comment] 2016-10-20 20:09
The lock file is to prevent people from updating d3 via drush. What's the contents of your d3.info file? Also, do you have any error messages in the console when you go to the dashboard?

**Comment by pguerr061703** [comment] 2016-10-21 03:30
root@ace-admin03:/var/www/html/sites/all/modules/contrib/d3# cat d3.info
name = D3
description = An API for creating visualizations from D3 libraries
core = 7.x
dependencies[] = libraries (>=2.0)
package = Visualization

; Information added by Drupal.org packaging script on 2015-02-21
version = "7.x-1.x-dev"
core = "7.x"
project = "d3"
datestamp = "1424552583"

**Comment by pguerr061703** [comment] 2016-10-21 10:46
<img width="939" alt="screenshot 2016-10-20 23 47 18" src="https://cloud.githubusercontent.com/assets/12171475/19595876/e5e91f9c-9759-11e6-9411-a3b1c62ab1f3.png">

I didn't see anything on dashboard console when I clicked on dashboard? (or Recent Log Messages)
Output of d3.info (below)
root@ace-admin03:/var/www/html/sites/all/modules/contrib/d3# cat d3.info
name = D3
description = An API for creating visualizations from D3 libraries
core = 7.x
dependencies[] = libraries (>=2.0)
package = Visualization

; Information added by Drupal.org packaging script on 2015-02-21
version = "7.x-1.x-dev"
core = "7.x"
project = "d3"
datestamp = "1424552583"

**Comment by pguerr061703** [comment] 2016-10-21 19:30
From Console:

![image](https://cloud.githubusercontent.com/assets/12171475/19609094/22a7f662-97a3-11e6-9e64-5923fadd54e6.png)

**Comment by mwidner** [comment] 2016-10-21 19:37
There's the problem. The site isn't loading the data properly, for some odd reason.  That /visualization/dashboard/data.json is the annotation data, but it's not being found at that URL. Try that URL in your browser and see what message you get. That URL doesn't resolve for me, but I suppose maybe that's an internal site?

**Comment by pguerr061703** [comment] 2016-10-21 20:07
I ran a find command and could not find the data.json file from the root of the LacunaStories directory

root@ace-linux13:/var/www/html# find . -name "data.json" -ls
root@ace-linux13:/var/www/html#

**Comment by mwidner** [comment] 2016-10-21 20:15
No, you wouldn't find it. That JSON file is dynamically generated by Lacuna. It's not in the filesystem anywhere.

**Comment by pguerr061703** [comment] 2016-10-21 20:23
How can I fix this? I am still at my whits end on a resolution.

I have 2 Lacuna sites and both are affected
The first Lacunasite(I showed you) the java console says the data.json is missing
The second Lacuna site, the java console doesnt show ANYTHING wrong, but the wheel is still spinning (see below)
![image](https://cloud.githubusercontent.com/assets/12171475/19610484/b742eee2-97aa-11e6-8209-cc717603f227.png)

**Comment by mwidner** [comment] 2016-10-21 20:29
When you visit: http://lacunatest.ace.fordham.edu/visualization/dashboard/data.json what, if anything, do you see?

Do you see anything in the system logs for the site? It'd be under Reports->Recent log messages. 
You'll likely find a bunch of warnings and such that you can probably ignore, but try looking at the logs right after visiting the dashboard. 

A few more questions: what version of PHP are you running? Ubuntu 16.04 is PHP 7 by default, isn't it? Drupal 7 doesn't fully support PHP 7 yet (https://www.drupal.org/node/2656548), so that could be the problem, too. Drupal 7.5 *should* work, but there are contributed modules that haven't caught up. If both sites are running on the same environment, then that suggests some PHP 7 incompatibility, too.

**Comment by pguerr061703** [comment] 2016-10-21 20:39
PHP Warning errors in "Recent Log Messages"

![image](https://cloud.githubusercontent.com/assets/12171475/19610841/967c9a44-97ac-11e6-8462-cbff0807ca36.png)

Page NOT FOUND when I go to http://lacunatest.ace.fordham.edu/visualization/dashboard/data.json 
![image](https://cloud.githubusercontent.com/assets/12171475/19610731/05282842-97ac-11e6-82f1-c0d312277cb3.png)


PHP version is 7.0.8
root@ace-admin03:/var/www/html/includes# php -v
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
root@ace-admin03:/var/www/html/includes#


root@ace-admin03:/var/www/html/includes# uname -a
Linux ace-admin03 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@ace-admin03:/var/www/html/includes#

I am at version 7.5.0 of Drupal ---- How easy is it to go to 7.5.1 ?
![image](https://cloud.githubusercontent.com/assets/12171475/19610908/f0890e1e-97ac-11e6-9736-b12c25400a9f.png)

**Comment by mwidner** [comment] 2016-10-21 20:42
It's easy enough to upgrade, but I don't think that's your problem. Those log messages don't help, either. That's a really common one that doesn't affect anything. 

Either way, the fact that the server can't find that URL is the problem. That's the URL you have the site installed at, right? Do you have [clean URLs enabled](https://www.drupal.org/docs/7/configuring-clean-urls/enable-clean-urls)?

**Comment by pguerr061703** [comment] 2016-10-21 20:53
Looks like Clean URLs is not (and cannot be enabled)..Not sure why?

![image](https://cloud.githubusercontent.com/assets/12171475/19611259/d4a85fc2-97ae-11e6-9b2a-d535a5e35e9f.png)

**Comment by mwidner** [comment] 2016-10-21 21:07
There's your problem. Lacuna doesn't work without clean urls enabled, which is a [server configuration issue](https://www.drupal.org/docs/7/configuring-clean-urls/enable-clean-urls#serverconfiguration). You'll need the mod_rewrite module for Apache.

**Closed** 2016-10-22 04:04 UTC
