### ISSUE TITLE
Issues with loading annotations in certain browsers for Lacuna Stories

### ISSUE THREAD

**Issue by pguerr061703** [PoeticMediaLab/LacunaStories#196] opened 2017-01-24 17:14 UTC

**Comment by mwidner** [comment] 2017-01-24 18:07
Thanks for the bug report. Can you tell me what version of Lacuna you're running? Also, the laptop is a touch screen laptop, isn't it?

Finally, is this Chrome causes problems only for this laptop, or for any computer it's tried on?

**Comment by pguerr061703** [comment] 2017-01-24 18:21
How do I determine the version of lacunstories ? (sorry, but I'm a noob at this)
I know its using drupal 7 on Ubuntu and I haven't updated it (since its been running at least 7months ago) . There about 3 available updates (7.x.) to for webform, media, 

I would have to ask the professor about the laptop (if its touch screen)
Chrome is problematic, regardless of the computer it is running on.
Firefox seems to be stable for Lacuna, from what I am hearing.

**Comment by pguerr061703** [comment] 2017-01-24 22:53
I am on Lacuna Stories 2.0 ( I believe ).
I remember talking with you back in Oct 2016. - closed case #167 
The d3 module caused the spinning wheel ( and I had to revert that module back ).
Is the D3 module issue fixed ?? Can I upgrade to latest version of Lacunastories (Ver# ?) ??
I have many faculty members using LacunaStories site and I am afraid of upgrading (that may cause issues that i won't be able to fix in a timely fashion ). 

Anyway this is what we learned ..regarding using LacunaStories on browsers:
Chrome works as expected with slightly different user interface than Firefox (PC / VDI / MAC) and Chrome on a Mac.  
On a PC or VDI (virtual desktop infrastructure) when using Chrome the end user will have to highlight the text and click the annotation button the right side of the browser.
Internet Explorer is not supported or working at all (regarding annotations)

Thank you for your help and time.
Patrick Guerrier
Systems Engineer
Fordham University

**Comment by mwidner** [comment] 2017-01-25 20:22
To find the version, go to Admin->Status Report. It may show the version of Lacuna there. We're currently on version 2.2.1, which I suspect you don't have yet. I haven't had any problems with Chrome myself, which is the only browser I tend to use. Not to say it's not a bug, but I may need more information to verify. 

Updating the site to the latest code should work just fine, but you might want to set up a test version of your site first just to be sure. Here's the documentation on updating:

https://github.com/PoeticMediaLab/LacunaStories#staying-up-to-date

**Comment by pguerr061703** [comment] 2017-01-25 20:25
What about the d3 module issue (spinning owl)?
If I update, I don't know if that will pull in the d3 module issue from #167

**Comment by mwidner** [comment] 2017-01-25 22:32
That issue is now fixed. I wouldn't run the update via 'drush up', just in case, but instead pull the latest code from our repository.

**Closed** 2017-04-25 20:54 UTC
